### ISSUE TITLE
Add better page structure

### ISSUE THREAD

**Issue by csswizardry** [inuitcss/inuitcss.github.io#2]
Header, footer, sidebar, columns, etc.

**Comment by csshugs** [comment]
@csswizardry There is no develop branch yet in this repository. For #3 (tkt-0003 branch), I branched off from tkt-0002 branch. Should we take that state as a new develop branch to have a central dev-branch?

**Comment by csswizardry** [comment]
Everything in here is just a mess right now haha. Branching off of `tkt-002` is probably the best idea.

**Comment by csshugs** [comment]
Ok, I now created a `develop` branch (branched off of `tkt-0002`). 

@csswizardry can we close this issue—its topic is not very specific—and provide specific issues on which we run the appropriate changes against?

**Comment by csshugs** [comment]
I close this since `tkt-0002`s work is already merged in `develop`.
